### ISSUE TITLE
idk how to customize it 

### ISSUE THREAD

**Issue by verbeel** [Pavui/Nebula4#1]
question i went to wiki to know how to customize the skin but, i couldn't find anything ^^" can i get some help?

**Comment by Pavui** [comment]
Are you using BD or Powercord?

**Comment by verbeel** [comment]
i'm using BD

**Comment by Pavui** [comment]
Ill add all the variables Nebula 4 uses later on today. Then you can download the file again.

**Comment by verbeel** [comment]
Awesome, thanks!
